- name: fetch helm upstream archive
  get_url:
    url: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: /root/helm-v{{ helm_version }}-linux-amd64.tar.gz
    mode: 0755
  register: helm_fetch

- name: extract helm from the archive
  shell: "tar -xvzf /root/helm-v{{ helm_version }}-linux-amd64.tar.gz -C /usr/local/bin --transform s:linux-amd64/:: linux-amd64/helm"
  when: helm_fetch.changed

- name: set ownership/mode on helm binary
  file:
    path: /usr/local/bin/helm
    owner: root
    group: root
    mode: 0755
