---
- name: remove libvirt image storage directory if it is a directory
  # not using file module because we don't want it deleted if it's not empty
  shell: /usr/bin/rmdir /var/lib/libvirt/images || true
  args:
    warn: no
  changed_when: false

- name: create a directory for libvirt image storage in home partition
  file:
    path: /home/libvirt-images
    state: directory
    owner: root
    group: root
    mode: 0755

- name: link libvirt image storage to home partition
  file:
    path: /var/lib/libvirt/images
    src: /home/libvirt-images
    state: link
