- name: update packages
  dnf:
    name: '*'
    state: latest

- name: install required packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - git
    - golang
    - gcc-go
    - libselinux-python
    - mercurial
    - screen
    - tmux
    - vagrant-libvirt

# remove the workaround when possible -- i fixed this upstream,
# but it's not in packages yet
- name: TEMPORARY vagrant fixup
  shell: sed -i -e 's/\(config.default_prefix.to_s\)$/\1.dup/' /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/set_name_of_domain.rb
