- name: clone kubernetes repo if not present
  git:
    repo: https://github.com/kubernetes/kubernetes
    dest: "{{ kube_user_home }}/kubernetes"
    update: no
  become: yes
  become_user: kube

- name: check whether kubernetes Vagrantfile needs patching
  shell: |
    grep KUBERNETES_VAGRANT_RSYNC_ARGS "{{ kube_user_home }}/kubernetes/Vagrantfile"
  register: kubernetes_vagrantfile_patched
  changed_when: false
  failed_when: false

- name: install patch command
  package:
    name: patch
    state: present
  when: kubernetes_vagrantfile_patched.rc != 0

- name: patch kubernetes Vagrantfile
  shell: |
    cd {{ kube_user_home }}/kubernetes
    curl 'https://patch-diff.githubusercontent.com/raw/kubernetes/kubernetes/pull/36740.patch' \
        | patch -p1
  become: yes
  become_user: kube
  when: kubernetes_vagrantfile_patched.rc != 0

- name: write kuberc
  copy:
    dest: /home/kube/kuberc
    content: |
      export PATH=${PATH}:/home/kube/kubernetes/third_party/etcd:/home/kube/kubernetes/_output/release-stage/client/linux-amd64/kubernetes/client/bin
      export KUBERNETES_PROVIDER=vagrant
      export VAGRANT_DEFAULT_PROVIDER=libvirt
      export KUBERNETES_VAGRANT_USE_NFS=true
      export NUM_NODES=4
      export KUBERNETES_NODE_MEMORY=5120
      export EXTRA_DOCKER_OPTS='--insecure-registry 192.168.0.0/16'
      ulimit -n 10000
    owner: kube
    group: kube
    mode: 0644

- name: install etcd the kube way
  shell: |
    cd {{ kube_user_home }}/kubernetes
    source ~/gimmerc
    source ~/kuberc
    ./hack/install-etcd.sh
  args:
    creates: /home/kube/kubernetes/third_party/etcd
  become: yes
  become_user: kube

- name: install build deps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker

- name: start necessary services
  service:
    name: "{{ item }}"
    state: running
    enabled: yes
  with_items:
    - docker
    - libvirtd
    - virtlogd

- name: chown docker socket to kube group
  file:
    path: /var/run/docker.sock
    group: kube

- name: set iptable rules for nfs
  iptables:
    chain: INPUT
    in_interface: "!{{ ansible_default_ipv4.interface }}"
    ip_version: ipv4
    protocol: "{{item.protocol}}"
    destination_port: "{{item.port}}"
    jump: ACCEPT
    comment: allow nfs mounts
  with_items:
    - { port: 111, protocol: 'udp' }
    - { port: 111, protocol: 'tcp' }
    - { port: 2049, protocol: 'udp' }
    - { port: 2049, protocol: 'tcp' }
    - { port: 20048, protocol: 'udp' }
    - { port: 20048, protocol: 'tcp' }
  when: ansible_default_ipv4
