- hosts: kube_host
  roles:
    - kubelunch_prereq
    - kube_user
    - home_libvirt_storage
    - role: minikube
      when: install_minikube|bool
    - role: vagrant_kubernetes
      when: install_vagrant_kubernetes|bool
    - role: gimme
      when: install_gimme|bool
    - role: kube_source
      when: install_kube_source|bool
    - role: kolla_source
      when: install_kolla_source|bool
    - role: docker_registry
      when: install_docker_registry|bool
