- hosts: kube_host
  roles:
    - kubelunch_prereq
    - kube_user
    - home_libvirt_storage
    - role: minikube
      when: install_minikube|bool
    - role: vagrant_kubernetes
      when: install_vagrant_kubernetes|bool
